package com.jadaptive.api.events;

import java.io.IOException;
import java.io.PrintWriter;
import java.io.StringWriter;

import com.jadaptive.api.entity.EntityType;
import com.jadaptive.api.repository.AbstractUUIDEntity;
import com.jadaptive.api.template.Column;
import com.jadaptive.api.template.FieldType;
import com.jadaptive.api.template.Template;

@Template(name = "Audit Event", resourceKey = "auditEvents", type = EntityType.COLLECTION)
public class AuditEvent extends AbstractUUIDEntity {

	@Column(name = "Resource Key", 
			description = "The identifier of this event", 
			searchable = true,
			type = FieldType.TEXT)
	String resourceKey;
		
	@Column(name = "Success", 
			description = "Did this event succeed?", 
			searchable = true,
			type = FieldType.BOOL)
	boolean success;
	
	@Column(name = "Error", 
			description = "The stacktrace of any error generated by this event",
			type = FieldType.TEXT_AREA)
	String error;
	
	public AuditEvent(String resourceKey) {

		this.resourceKey = resourceKey;
		this.success = true;
	}
	
	public AuditEvent(String resourceKey, Throwable e) {
		this.resourceKey = resourceKey;
		this.success = false;
		this.error = generateExceptionText(e);
	}

	protected void markSuccess() {
		this.success = true;
	}
	
	private String generateExceptionText(Throwable e) {
		try(StringWriter w = new StringWriter()) {
			e.printStackTrace(new PrintWriter(w));
			return w.toString();
		} catch (IOException e1) {
			throw new IllegalStateException(e1.getMessage(), e1);
		}
	}

	public String getResourceKey() {
		return resourceKey;
	}

	public void setResourceKey(String resourceKey) {
		this.resourceKey = resourceKey;
	}

	public boolean isSuccess() {
		return success;
	}
	
	public String getError() {
		return error;
	}
}
